# Generated by Django 2.0.3 on 2018-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(),
        ),
    ]
